site_name: Luftqualität Explorer für Basel-Stadt
site_url: https://example.com/

nav:
  - Home: index.md
  - 'Benutzeranleitung':
    - 'Info': 'info.md'
    - 'Statistiken': 'stats.md'
    - 'Grafiken': 'plots.md'
    - 'Grenzwert Überschreitungen': 'exceedances.md'
  - About: about.md
  - 'Versionen': 'versions.md'

theme:
    name: readthedocs
